### ISSUE TITLE
This happens on log in

### ISSUE THREAD

**Issue by JamesWilliams500** [Fiurs-Hearth/WIIIUI#11]
I have zero addons I have reloaded a bunch of times and I still get this.

https://i.imgur.com/mumREL5.jpeg
[https://i.imgur.com/mumREL5.jpeg](url)

**Comment by Fiurs-Hearth** [comment]
I can see several addons being active at the same time as the WIIIUI, please disable the other addons and try again.

Also try and see if this fixes it:
"Options not saving is likely because your files are set to 'Read only', please look up how to remove 'Read only' as it is different depending on your OS."
Remove "Read only" for the entire folder and its files

**Comment by Ragnarockin** [comment]
I'm afraid I'm having the same issue with no other addons present. WIII UI is being marked outdated so i think its a client version behind. 

-I have removed the read only flag from my files.
-video settings have been adjusted as to not auto detect.
-I've tried logging in through battle.net app and manually, resulting in the same interface bug. 
-bug persists between different characters.
-clicking reload ui, reloads the ui but the problem continues. The big red button in the center of screen has the same effect.
-making changes to the visible configuration options has no effect and do not carry over on reloading ui.

If i can do anything else to help diagnose whats going on with it let me know, this is a killer addon and would love to get it working

**Comment by Fiurs-Hearth** [comment]
I think I know the reason why it is not working for the two of you.
Are you playing on WoW Classic/SoM?

Unfortunately the addon is not currently working on anything except of WoW Vanilla (not to be confused with Classic/SoM) BUT I am currently working on porting it for retail and Classic/SoM.

**Comment by Ragnarockin** [comment]
ah! i see, yes this would be the case for me. i had tested it on both SoM and Classic thinking SoM might have been fudging it, but that wouldnt be the case would it?

in that case, godspeed sir, i hope you have a smooth transition to Classic/SoM with minimal bugs.
