### ISSUE TITLE
UI error upon selecting "Offhand" option on "Top right weapon icon"

### ISSUE THREAD

**Issue by internetveterano** [Fiurs-Hearth/WIIIUI#12]
Ever since the last update of the WIIIUI addon this happens upon reload when I select the "offhand" option on the WIIIUI menu:

![WoWScrnShot_022722_210515](https://user-images.githubusercontent.com/100542558/155906111-eecb1f4e-3d7b-4451-b739-fcf5b0c995c1.jpg)

More info: My script memory size is set to "0" as per recommended. My display resolution is set to my native 1920x1080 with no UI scaling enabled. This happens with the "Enable customize settings" option being enabled or disabled. 

To recreate the error you should only have to activate "Offhand" on "Top right weapon icon" and then reload UI:

![image](https://user-images.githubusercontent.com/100542558/155906391-9f822dbd-b0ab-4bc0-a117-fc19052d1dc4.png)

(I'm not reloading every time I change an option by the way, only when the addon tells me to).

I tried:

- Disabling all other addons
- Deleting my WDB folder
- Deleting my WTF folder
- Deleting my WDB and WTF folder and then reinstalling the addon

I've really been enjoying this addon, it's my favorite UI so far, so thanks in advance!

**Comment by Fiurs-Hearth** [comment]
Thanks for the report, I will fix this as soon as possible!

**Comment by Fiurs-Hearth** [comment]
As I can not replicate this bug (tried following your instructions and more) could you explain more exactly on how you replicate this bug?

You can add me on Discord if you want (Fiur#8658)

**Comment by Fiurs-Hearth** [comment]
No response, closing issue.
