### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by versaceversace** [Fiurs-Hearth/WIIIUI#13]
Is there any way we can see the latency (ms) in game? I couldn't find a setting and nothing I found online works so far

**Comment by Fiurs-Hearth** [comment]
I have added latency (ms) to the armor values as a temporary fix.

Just hover over the armor icon and it will be shown at the bottom of the tooltip box.

**Comment by bruceanhuifs** [comment]
> I have added latency (ms) to the armor values as a temporary fix.
> 
> Just hover over the armor icon and it will be shown at the bottom of the tooltip box.

how to add latency to the armor values ? ty
