### ISSUE TITLE
using WIIIUI breaks some of my other addons

### ISSUE THREAD

**Issue by nobrains21** [Fiurs-Hearth/WIIIUI#2]
Im pretty new to this and my knowledge and understanding of how this all works is limited, but ill try my best to explain. Every time i try using particular addon (with yours being enabled) - it gives me the same kind of error about [_an attempt to call global `time' (a number value)_]:
![WoWScrnShot_011522_134631](https://user-images.githubusercontent.com/59528934/149621438-310a6590-7a1b-4501-b9a4-6319d168b726.png)
Disabling your addon and reloading ui makes other addons work again.
___
The addons that break for me are:

- Looking for Turtles(turtle wow specific) [697](https://github.com/CosminPOP/LFT/blob/master/LFT.lua#L697)

- WIM("instant messages" addon) [449](https://github.com/shirsig/WIM/blob/master/WIM.lua#L449)

- Aux(auction ui replacement) [19](https://github.com/shirsig/aux-addon-vanilla/blob/master/core/history.lua#L19)
___
I would assume that LFT.lua:697 text references line number 697 in that file? Ive listed the lines it references for other 2 addons above(with links to the place i got them from). If you want me to provide something else - tell me.

**Comment by Fiurs-Hearth** [comment]
This issue should now be resolved.
The fix has been merged into master, you can re-download the addon now and the problem should be fixed.

Thanks for reporting the issue, your report was great!
