### ISSUE TITLE
Black field to the right covers additional chat tabs.

### ISSUE THREAD

**Issue by nobrains21** [Fiurs-Hearth/WIIIUI#3]
Moving chat in to the black field to the right makes it so you can not see additional tabs, this black field appears to be on top of them.
You can not see them, but you can still click on them and see text in the chat box.
![1](https://user-images.githubusercontent.com/59528934/149626837-cbdbcd15-6b1b-4173-a7c3-3082a74f8f77.png)
![2](https://user-images.githubusercontent.com/59528934/149626841-2aa7d9cc-71c9-4833-81b1-5eaf029dda02.png)

**Comment by nobrains21** [comment]
im not using any chat mods or anything like that, that is a default chat with tabs i made for it using built in tools.

**Comment by Fiurs-Hearth** [comment]
Thanks for reporting, I will commit the fix soon.
