### ISSUE TITLE
Ultrawide support

### ISSUE THREAD

**Issue by SpirriX** [Fiurs-Hearth/WIIIUI#9]
Does not scale well with ultrawide resolution. I'm on 3440x1440, and it looks bonkers. Only way to make stuff connect at the bottom is to set the scale to minimum 375. This makes the UI elements HUGE.

**Comment by Fiurs-Hearth** [comment]
This can now be solved with the latest feature added.
See link: https://github.com/Fiurs-Hearth/WIIIUI#here-are-some-example-edits
